version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '08:30'
      timezone: 'America/Sao_Paulo'
    allow:
      - dependency-name: '@vtex/*'
    ignored_updates:
      - match:
          update_type: 'semver:major'
    # automerged_updates:
    #   - match:
    #       update_type: 'semver:patch'
    open-pull-requests-limit: 5
    reviewers:
      - 'vtex/faststore'
      - 'vtex/store-framework'
