[[plugins]]
  package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "/*"
  to = "https://storetheme.vtex.com/:splat?workspace=nocache"
  status = 200
  force = true
  headers = {X-Forwarded-Host="storecomponents.myvtexprod.com", cache-control="no-cache", pragma="no-cache"}
